# Generated by Django 5.0.4 on 2024-04-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='タイトル', max_length=255)),
                ('body', models.TextField(db_comment='内容')),
                ('is_public', models.BooleanField(db_comment='表示・非表示', default=True)),
                ('published_at', models.DateTimeField(db_comment='公開日')),
            ],
        ),
    ]
